DEMO_CATEGORIES = [
    {
        "id": 1,
        "name": "Продукти та супермаркети",
        "nameEn": "Groceries and supermarkets",
    },
    {"id": 2, "name": "Продукти", "nameEn": "Products", "parentId": 1},
    {
        "id": 3,
        "name": "Алкоголь, тютюн",
        "nameEn": "Alcohol, tobacco",
        "parentId": 1,
    },
    {"id": 4, "name": "Інше", "nameEn": "Other", "parentId": 1},
    {"id": 5, "name": "Кафе та ресторани", "nameEn": "Cafes and restaurants"},
    {"id": 6, "name": "Ресторани", "nameEn": "Restaurants", "parentId": 5},
    {"id": 7, "name": "Фаст-фуд", "nameEn": "Fast food", "parentId": 5},
    {"id": 8, "name": "Бар", "nameEn": "Bar", "parentId": 5},
    {"id": 9, "name": "Кафе", "nameEn": "Cafe", "parentId": 5},
    {"id": 10, "name": "Покупки", "nameEn": "Shopping"},
    {
        "id": 11,
        "name": "Одяг та взуття",
        "nameEn": "Clothing and footwear",
        "parentId": 10,
    },
    {
        "id": 12,
        "name": "Ювелірні вироби, аксесуари",
        "nameEn": "Jewelry, accessories",
        "parentId": 10,
    },
    {"id": 13, "name": "Дім, сад", "nameEn": "Home, garden", "parentId": 10},
    {"id": 14, "name": "Подарунки", "nameEn": "Gifts", "parentId": 10},
    {"id": 15, "name": "Канцтовари", "nameEn": "Stationery", "parentId": 10},
    {"id": 16, "name": "Приладдя", "nameEn": "Supplies", "parentId": 10},
    {
        "id": 17,
        "name": "Електроніка та аксесуари",
        "nameEn": "Electronics and accessories",
        "parentId": 10,
    },
    {"id": 18, "name": "Тварини", "nameEn": "Pets", "parentId": 10},
    {"id": 19, "name": "Квіти", "nameEn": "Flowers", "parentId": 10},
    {
        "id": 20,
        "name": "Електроніка та аксесуари",
        "nameEn": "Electronics and accessories",
        "parentId": 10,
    },
    {"id": 21, "name": "Здоров'я та краса", "nameEn": "Health and beauty"},
    {"id": 22, "name": "Аптека", "nameEn": "Pharmacy", "parentId": 21},
    {"id": 23, "name": "Краса", "nameEn": "Beauty", "parentId": 21},
    {
        "id": 24,
        "name": "Медичні послуги",
        "nameEn": "Medical services",
        "parentId": 21,
    },
    {
        "id": 25,
        "name": "Велнес, СПА",
        "nameEn": "Wellness, SPA",
        "parentId": 21,
    },
    {"id": 26, "name": "Розваги", "nameEn": "Entertainment"},
    {"id": 27, "name": "Музика", "nameEn": "Music", "parentId": 26},
    {"id": 28, "name": "Мистецтво", "nameEn": "Art", "parentId": 26},
    {
        "id": 29,
        "name": "Лотерея, азартні ігри",
        "nameEn": "Lottery, gambling",
        "parentId": 26,
    },
    {
        "id": 30,
        "name": "Хобі, дозвілля",
        "nameEn": "Hobbies, leisure",
        "parentId": 26,
    },
    {
        "id": 31,
        "name": "Життєві події",
        "nameEn": "Life events",
        "parentId": 26,
    },
    {"id": 32, "name": "Спорт", "nameEn": "Sport", "parentId": 26},
    {"id": 33, "name": "Відпочинок", "nameEn": "Recreation", "parentId": 26},
    {
        "id": 35,
        "name": "Побутова техніка",
        "nameEn": "Home appliances",
        "parentId": 10,
    },
    {"id": 36, "name": "Благодійність", "nameEn": "Charity"},
    {"id": 37, "name": "Кіно", "nameEn": "Cinema"},
    {
        "id": 38,
        "name": "Кіно, театр",
        "nameEn": "Cinema, theater",
        "parentId": 37,
    },
    {
        "id": 39,
        "name": "ТБ, стрімінг",
        "nameEn": "TV, streaming",
        "parentId": 37,
    },
    {"id": 40, "name": "Транспорт", "nameEn": "Transport"},
    {"id": 41, "name": "Пальне", "nameEn": "Fuel", "parentId": 40},
    {"id": 42, "name": "Паркування", "nameEn": "Parking", "parentId": 40},
    {"id": 43, "name": "Страхування", "nameEn": "Insurance", "parentId": 40},
    {
        "id": 44,
        "name": "Технічне обслуговування",
        "nameEn": "Maintenance",
        "parentId": 40,
    },
    {"id": 45, "name": "Лізинг", "nameEn": "Leasing", "parentId": 40},
    {"id": 46, "name": "Житло", "nameEn": "Housing"},
    {
        "id": 47,
        "name": "Комунальні послуги",
        "nameEn": "Utilities",
        "parentId": 46,
    },
    {
        "id": 48,
        "name": "Іпотека на житло",
        "nameEn": "Housing mortgage",
        "parentId": 46,
    },
    {"id": 49, "name": "Оренда", "nameEn": "Rent", "parentId": 46},
    {"id": 50, "name": "Ремонт", "nameEn": "Renovation", "parentId": 46},
    {"id": 51, "name": "Страхування", "nameEn": "Insurance", "parentId": 46},
    {"id": 52, "name": "Послуги", "nameEn": "Services", "parentId": 46},
    {"id": 53, "name": "Подорожі", "nameEn": "Travel"},
    {"id": 54, "name": "Авіаквитки", "nameEn": "Air tickets", "parentId": 53},
    {"id": 55, "name": "Готелі", "nameEn": "Hotels", "parentId": 53},
    {
        "id": 56,
        "name": "Громадський транспорт",
        "nameEn": "Public transport",
        "parentId": 53,
    },
    {
        "id": 57,
        "name": "Квитки на поїзд",
        "nameEn": "Train tickets",
        "parentId": 53,
    },
    {"id": 58, "name": "Оренда авто", "nameEn": "Car rental", "parentId": 53},
    {
        "id": 59,
        "name": "Ділові поїздки",
        "nameEn": "Business trips",
        "parentId": 53,
    },
    {
        "id": 60,
        "name": "Дальні поїздки",
        "nameEn": "Long trips",
        "parentId": 53,
    },
    {"id": 61, "name": "Таксі", "nameEn": "Taxi", "parentId": 53},
    {"id": 62, "name": "Duty Free", "nameEn": "Duty Free"},
    {"id": 63, "name": "Інше", "nameEn": "Other", "parentId": 62},
    {"id": 64, "name": "Ремонт", "nameEn": "Renovation"},
    {"id": 65, "name": "Інше", "nameEn": "Other", "parentId": 64},
    {"id": 66, "name": "Освіта", "nameEn": "Education"},
    {"id": 67, "name": "Книги", "nameEn": "Books", "parentId": 66},
    {"id": 68, "name": "Аудіокниги", "nameEn": "Audiobooks", "parentId": 66},
    {"id": 69, "name": "Інше", "nameEn": "Other", "parentId": 66},
    {"id": 70, "name": "Фінансові витрати", "nameEn": "Financial expenses"},
    {
        "id": 71,
        "name": "Консультації",
        "nameEn": "Consultations",
        "parentId": 70,
    },
    {"id": 72, "name": "Поштові сервіси", "nameEn": "Postal services"},
    {"id": 73, "name": "Доставка", "nameEn": "Delivery", "parentId": 72},
    {"id": 74, "name": "Інше", "nameEn": "Other", "parentId": 72},
    {"id": 75, "name": "Дохід", "nameEn": "Income"},
    {
        "id": 76,
        "name": "Зарахування зі свого рахунку",
        "nameEn": "Transfer from own account",
        "parentId": 75,
    },
    {
        "id": 77,
        "name": "Зарахування з чужого рахунку",
        "nameEn": "Transfer from another account",
        "parentId": 75,
    },
    {
        "id": 78,
        "name": "Поповнення готівкою",
        "nameEn": "Cash deposit",
        "parentId": 75,
    },
    {
        "id": 79,
        "name": "Чеки, купони",
        "nameEn": "Checks, coupons",
        "parentId": 75,
    },
    {"id": 80, "name": "Аліменти", "nameEn": "Alimony", "parentId": 75},
    {
        "id": 81,
        "name": "Виплати та гранти",
        "nameEn": "Payments and grants",
        "parentId": 75,
    },
    {"id": 82, "name": "Подарунки", "nameEn": "Gifts", "parentId": 75},
    {
        "id": 83,
        "name": "Відсотки, дивіденди",
        "nameEn": "Interest, dividends",
        "parentId": 75,
    },
    {
        "id": 84,
        "name": "Кредитування, оренда",
        "nameEn": "Lending, rental",
        "parentId": 75,
    },
    {
        "id": 85,
        "name": "Лотерея, азартні ігри",
        "nameEn": "Lottery, gambling",
        "parentId": 75,
    },
    {
        "id": 86,
        "name": "Відшкодування (податки, покупка)",
        "nameEn": "Refunds (taxes, purchase)",
        "parentId": 75,
    },
    {"id": 87, "name": "Продаж", "nameEn": "Sale", "parentId": 75},
    {"id": 88, "name": "Зарплата", "nameEn": "Salary", "parentId": 75},
    {
        "id": 89,
        "name": "Надання послуг",
        "nameEn": "Providing services",
        "parentId": 75,
    },
    {"id": 90, "name": "Перекази", "nameEn": "Transfers"},
    {
        "id": 91,
        "name": "Переказ на свій рахунок",
        "nameEn": "Transfer to own account",
        "parentId": 90,
    },
    {
        "id": 92,
        "name": "Переказ на чужий рахунок",
        "nameEn": "Transfer to another account",
        "parentId": 90,
    },
    {
        "id": 93,
        "name": "Зняття готівки",
        "nameEn": "Cash withdrawal",
        "parentId": 90,
    },
    {
        "id": 94,
        "name": "Зв'язок, комп'ютери",
        "nameEn": "Communication, computers",
    },
    {"id": 95, "name": "Інтернет", "nameEn": "Internet", "parentId": 94},
    {
        "id": 96,
        "name": "Телефонія, мобільний зв'язок",
        "nameEn": "Telephony, mobile communication",
        "parentId": 94,
    },
    {
        "id": 97,
        "name": "Програмне забезпечення, додатки, ігри",
        "nameEn": "Software, apps, games",
        "parentId": 94,
    },
    {"id": 98, "name": "Зобов’язання", "nameEn": "Obligations"},
    {"id": 99, "name": "Податки", "nameEn": "Taxes", "parentId": 98},
    {
        "id": 100,
        "name": "Комісії, збори",
        "nameEn": "Fees, charges",
        "parentId": 98,
    },
    {"id": 101, "name": "Аліменти", "nameEn": "Alimony", "parentId": 98},
    {"id": 102, "name": "Штрафи", "nameEn": "Fines", "parentId": 98},
    {"id": 103, "name": "Інше", "nameEn": "Other", "parentId": 10},
    {"id": 104, "name": "Інше", "nameEn": "Other", "parentId": 26},
    {"id": 105, "name": "Інше", "nameEn": "Other", "parentId": 36},
    {"id": 106, "name": "Інше", "nameEn": "Other", "parentId": 40},
    {"id": 107, "name": "Інше", "nameEn": "Other", "parentId": 46},
    {"id": 108, "name": "Інше", "nameEn": "Other", "parentId": 53},
    {"id": 109, "name": "Інше", "nameEn": "Other", "parentId": 5},
    {"id": 110, "name": "Інше", "nameEn": "Other", "parentId": 37},
    {"id": 111, "name": "Інше", "nameEn": "Other", "parentId": 21},
    {"id": 112, "name": "Інше", "nameEn": "Other", "parentId": 75},
    {"id": 113, "name": "Інше", "nameEn": "Other", "parentId": 90},
    {"id": 114, "name": "Інше", "nameEn": "Other", "parentId": 94},
    {"id": 115, "name": "Інше", "nameEn": "Other", "parentId": 70},
    {"id": 116, "name": "Інше", "nameEn": "Other", "parentId": 98},
    {"id": 117, "name": "Розбивання", "nameEn": "Split"},
    {
        "id": 118,
        "name": "Обмін: списання",
        "nameEn": "Exchange: withdrawal",
        "parentId": 90,
    },
    {
        "id": 119,
        "name": "Обмін: надходження",
        "nameEn": "Exchange: deposit",
        "parentId": 75,
    },
    {
        "id": 120,
        "name": "Збройні Сили України",
        "nameEn": "Armed Force of Ukraine",
        "parentId": 36,
    },
    {
        "id": 121,
        "name": "Медицина й лікування",
        "nameEn": "Medicine and treatment",
        "parentId": 36,
    },
    {"id": 122, "name": "Освіта", "nameEn": "Education", "parentId": 36},
    {
        "id": 123,
        "name": "Екологія та довкілля",
        "nameEn": "Ecology and environment",
        "parentId": 36,
    },
    {
        "id": 124,
        "name": "Культура та спадщина",
        "nameEn": "Culture and heritage",
        "parentId": 36,
    },
    {
        "id": 125,
        "name": "Надзвичайні ситуації",
        "nameEn": "Emergency situations",
        "parentId": 36,
    },
    {
        "id": 126,
        "name": "Міжнародні гуманітарні фонди",
        "nameEn": "International humanitarian funds",
        "parentId": 36,
    },
    {"id": 127, "name": "Наука", "nameEn": "Science", "parentId": 36},
    {"id": 128, "name": "Спорт", "nameEn": "Sport", "parentId": 36},
    {"id": 129, "name": "Тварини", "nameEn": "Animals", "parentId": 36},
    {
        "id": 130,
        "name": "Соціальна допомога",
        "nameEn": "Social assistance",
        "parentId": 36,
    },
    {"id": 1002, "name": "Test1", "parentId": 1},
    {"id": 1003, "name": "", "parentId": 1},
]
